setw -g mode-keys vi

set -g mouse on

set -g base-index 1
set -g default-terminal "screen-256color"

# Panes
setw -g pane-base-index 1

# Copy mouse selection to clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# Reload
bind r source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key N display-popup -E "bash ~/work/dev-scripts/tmux-sessionizer"
bind-key S display-popup -E "bash ~/work/dev-scripts/tmux-session-select"

unbind C-b
set-option -g prefix C-a

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
set -g @plugin "arcticicestudio/nord-tmux"
