require("hyprland.vars")
require("hyprland.env")
require("hyprland.monitors")
require("hyprland.settings")
require("hyprland.input")
require("hyprland.rules")
require("hyprland.keybinds")
require("hyprland.exec")
